// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Asd } from "./../../systems/IncrementSystem.sol";

interface IIncrementSystem {
  function increment(Asd memory asd) external returns (uint32);
}
